FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /

# Copy csproj and restore as distinct layers
COPY *.sln ./
COPY nuget.config ./
COPY DemoBank.Account.Presentation/DemoBank.API.csproj DemoBank.API/
COPY DemoBank.Account.Domain/DemoBank.Domain.csproj DemoBank.Domain/
COPY DemoBank.Account.Data/DemoBank.Infrastructure.Data.csproj DemoBank.Infrastructure.Data/
COPY DemoBank.CrossCutting/DemoBank.CrossCutting.csproj DemoBank.CrossCutting/
COPY DemoBank.Test/DemoBank.Test.csproj DemoBank.Test/
COPY . ./
RUN dotnet restore

# Copy everything else and build
WORKDIR /DemoBank
#RUN mv appsettings.Docker.json appsettings.json
RUN dotnet publish -c Release -o /app

# Build runtime image
FROM microsoft/dotnet:2.2-aspnetcore-runtime

WORKDIR /app
COPY --from=build-env /app .
ENTRYPOINT ["dotnet", "DemoBank.API.dll"]

EXPOSE 80